### ISSUE TITLE
RemoveMax falla caso de prueba

### ISSUE THREAD

**Issue by IvonneMont** [IvonneMont/pai-2020-tarea-08#6]
8 11 2 -10 18 10 11 17 24 -4 -13 2 15 -16 -12 
24 18 17 15 11 10 11 2 8 -4 -13 -10 2 -16 -12 

 maximo:24
18 11 17 15 -12 10 11 2 8 -4 -13 -10 2 -16 

 maximo:18
15 11 17 2 -12 10 11 2 8 -4 -13 -10 -16 

 maximo:15
17 11 8 2 -12 10 11 2 -16 -4 -13 -10 

 maximo:17
11 11 8 2 -12 10 -10 2 -16 -4 -13

**Comment by isalopezh** [comment]
La línea que dice “maximo: número “ es lo que arroja la función y la segunda es el arreglo que se ingresó?

**Comment by IvonneMont** [comment]
La segunda es lo que queda después de extraer el máximo, el arreglo original es 8 11 2 -10 18 10 11 17 24 -4 -13 2 15 -16 -12, después de que se ingresa al montículo queda 24 18 17 15 11 10 11 2 8 -4 -13 -10 2 -16 -12, y le voy quitando el mas grande

**Comment by isalopezh** [comment]
ya le hice unas correcciones y parece funcionar bien.

**Comment by IvonneMont** [comment]
Pasó el caso de prueba
