### ISSUE TITLE
Insert falla un caso de prueba 

### ISSUE THREAD

**Issue by IvonneMont** [IvonneMont/pai-2020-tarea-08#7]
Al insertar el flujo -10 15 -7 -20 18 -23 0 10 12 -14 14 13 -25 -9 18
El montículo obtenido es:
14 18 10 13 18 -23 0 -10 -7 -14 -20 12 -25 -9 15 

14 no es el máximo, es 18

**Comment by isalopezh** [comment]
Jaja justo iba a comentar eso, metí el arreglo: arr=[8,11,2,10,18,10,11] y me arroja el montículo [11,18,11, 2,10,8,10], estuve haciendo un par de pruebas mas y genera un 0 antes de realizar la primer inserción

**Comment by isalopezh** [comment]
Areglo que ingresa:
33 36 27 15 43 35 36 

 El monticulo es:
0 33 

 El monticulo es:
36 33 0 

 El monticulo es:
36 33 0 27 

 El monticulo es:
36 33 0 27 15 

 El monticulo es:
36 43 0 27 15 33 

 El monticulo es:
36 43 0 27 15 33 35 

 El monticulo es:
36 43 36 27 15 33 35 0

**Comment by IvonneMont** [comment]
Se solucionó inicializando en -1 el valor de n y se hizó una modificación el la función bottomUpHeapify
